version: '3.8'

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: accidentes_craper
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    entrypoint: /bin/sh
    command: -c "ollama serve & ollama pull mistral && wait"
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db
      - ollama
    environment:
      - DATABASE_URL=mysql+pymysql://root:example@db:3306/accidentes_craper
      - OLLAMA_BASE_URL=http://ollama:11434

volumes:
  db_data:
  ollama_data: 