version: '3.8'

services:
  db:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: accidentes_craper
      MYSQL_USER: root
      MYSQL_PASSWORD: example
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: always

  app:
    build: .
    depends_on:
      - db
      - ollama
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: accidentes_craper
      OLLAMA_HOST: ollama
      OLLAMA_PORT: 11434
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: pipenv run uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  db_data:
  ollama_data: 